arb-dir: lib/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
untranslated-messages-file: untranslated_detailed.txt
output-class: AppLocalizations
synthetic-package: false
report-untracked-files: true
required-resource-attributes: description, meaning